SafeNetATM/Models/BaseModel.cs
using System.ComponentModel.DataAnnotations;

namespace SafeNetATM.Models {
    public abstract class BaseModel {
        [Key]
        public int Id { get; set; }
    }
}

SafeNetATM/Models/Denomination.cs
namespace SafeNetATM.Models {
    public class Denomination: BaseModel {
        public int Value { get; set; }
        public int InitialQty { get; set; }
        public int RemainingQty { get; set; }
    }
}

SafeNetATM/ViewModels/AtmDenominationsVm.cs
using System.Collections.Generic;

namespace SafeNetATM.ViewModels {
    public class AtmDenominationsVm {
        public string Result { get; set; }
        public string Title { get; set; }
        public List<DenominationVm> Denominations { get; set; }

        public AtmDenominationsVm() {
            Denominations = new List<DenominationVm>();
        }
    }
}

SafeNetATM/ViewModels/DenominationVm.cs
namespace SafeNetATM.ViewModels {
    public class DenominationVm {
        public int Value { get; set; }
        public int Count { get; set; }
    }
}

SafeNetATM/Controllers/ATMController.cs
using SafeNetATM.Helpers;
using SafeNetATM.Models;
using SafeNetATM.Repository;
using SafeNetATM.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace SafeNetATM.Controllers {
    public class ATMController : Controller {
        private DenominationRepository _denonminationRepository;

        public ATMController() {
            _denonminationRepository = new DenominationRepository();
        }

        public ActionResult Index() {
            return View();
        }

        [HttpGet]
        public ActionResult ProcessRequest(string value) {
            List<string> parts = value.Split(' ').ToList();

            if (parts.Count > 0) {
                // Browsers prevent you from closing a window that a script didn't open, so "Q"uit handled in UI
                //  since results for the calls here are rendered in the result div
                switch (parts[0].ToUpper()) {
                    case "R":
                        // restock requires a single parameter
                        if (parts.Count > 1)
                            break;
                        return Restock();
                    case "W":
                        // withdraw requires 2 parameters
                        if (parts.Count != 2)
                            break;
                        return Withdraw(parts[1]);
                    case "I":
                        if (parts.Count < 2)
                            break;

                        parts.RemoveAt(0);
                        return GetBalance(parts);
                    //case "Q":
                    //    // Browsers prevent you from closing a window that a script didn't open, so just redirect to home page
                    //    return RedirectToAction("Index", "Home");
                }
            }

            return InvalidCommand(); 
        }

        private JsonResult InvalidCommand() {
            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return Json(new { success = false, responseText = "Invalid Command" }, JsonRequestBehavior.AllowGet);
        }

        private ActionResult Restock() {
            var result = new AtmDenominationsVm();

            var denominations = _denonminationRepository.Collection().OrderByDescending(x => x.Value).ToList();
            DenominationUtils.Restock(denominations);
            _denonminationRepository.Commit();

            AddRemainingBalance(result, denominations);

            return PartialView("_Restock", result);
        }

        private ActionResult Withdraw(string amount) {
            if (!int.TryParse(amount.Replace("$", ""), out int remainder))
                return InvalidCommand();

            var result = new AtmDenominationsVm {
                Result = $"Success: Dispensed {amount}"
            };

            var denominations = _denonminationRepository.Collection().OrderByDescending(x => x.Value).ToList();
            
            // Don't have a way to do a rollback for the memory table, so updates to the remainingqty end up
            // modifying the actual value even if it's going to fail. 
            if (!DenominationUtils.HasEnoughFunds(denominations, remainder)) {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { success = false, responseText = "Failure: insufficient funds" }, JsonRequestBehavior.AllowGet);
            }

            // This raises the question, what if 2 people try to perform a withdraw at the same time? 
            //  Not an issue for an ATM, but would need a Pessimistic way to handle this for other types of implementations
            DenominationUtils.Withdraw(denominations, ref remainder);
                           
            _denonminationRepository.Commit();

            AddRemainingBalance(result, denominations);
            return PartialView("_Withdraw", result);
        }

        private void AddRemainingBalance(AtmDenominationsVm viewModel, List<Denomination> denominations) {
            viewModel.Title = "Machine balance:";

            foreach (Denomination item in denominations)
                viewModel.Denominations.Add(new DenominationVm { Value = item.Value, Count = item.RemainingQty });
        }

        private ActionResult GetBalance(List<string> denominations) {
            var result = new AtmDenominationsVm();
            foreach (string value in denominations) {
                if (int.TryParse(value.Replace("$", ""), out int x)) {
                    var item = _denonminationRepository.GetByValue(x);
                    if (item != null)
                        result.Denominations.Add(new DenominationVm { Value = item.Value, Count = item.RemainingQty });
                    else
                        // If we can't find the value, there's something wrong with the request string
                        return InvalidCommand();
                } else {
                    // If we can't find the value, there's something wrong with the request string
                    return InvalidCommand();
                }
            }
            return PartialView("_Balance", result);
        }
    }
}

SafeNetATM/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SafeNetATM.Controllers {
    public class HomeController : Controller {
        public ActionResult Index() {
            return View();
        }

        public ActionResult About() {
            ViewBag.Message = "SafeNet ATM development problem";
            return View();
        }

        public ActionResult Contact() {
            return View();
        }
    }
}

SafeNetATM/Views/ATM/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>ATM Processing</h2>
<div>

    <div>
        <div class="input-group">
            <span class="input-group-addon">Enter Request</span>
            <input id="requestInput" type="text" class="form-control" name="request">
            <button id="buttonRequest" type="button" class="btn btn-default" onclick="processRequest()">Submit Request</button>
        </div>
    </div>

    <br />
    <div id="requestResult">
    </div>
</div>

<script type="text/javascript">
    function processRequest() {
        var value = document.getElementById("requestInput").value;
        // browsers prevent you from actually closing a page that wasn't opened by the same script. 
        // So the only option I saw was to redirect to home page.
        if (value.toUpperCase() == "Q") {
            RedirectToHome();
        }

        var urlPartial = '@Url.Action("ProcessRequest", "ATM")?value=' + value;
        $.ajax
        ({
            url: urlPartial,
            type: 'GET',
            contentType: "application/json",
            success: function(data) {
                $("#requestResult").html(data);
            },
            error: function (response) {
                $("#requestResult").html(response.responseJSON.responseText);
            }
        });
    }


    function RedirectToHome()    {
        var url = "/Home";
        window.location = url;
    }
</script>

SafeNetATM/Views/ATM/_Balance.cshtml
@using SafeNetATM.ViewModels
@model SafeNetATM.ViewModels.AtmDenominationsVm

<div>
    <div class="messageText">@Model.Result</div>

    <table>
        @foreach (DenominationVm denomination in Model.Denominations) {
        <tr>
            <td>$@denomination.Value</td>
            <td>@denomination.Count</td>

        </tr>
        }
    </table>
</div>

SafeNetATM/Views/ATM/_Restock.cshtml
@using SafeNetATM.ViewModels
@model SafeNetATM.ViewModels.AtmDenominationsVm

<div>
    <div class="messageText">@Model.Result</div>
    <div class="messageText">@Model.Title</div>

    <table>
        @foreach (DenominationVm denomination in Model.Denominations) {
        <tr>
            <td>$@denomination.Value</td>
            <td>@denomination.Count</td>

        </tr>
        }
    </table>
</div>

SafeNetATM/Views/ATM/_Withdraw.cshtml
@using SafeNetATM.ViewModels
@model SafeNetATM.ViewModels.AtmDenominationsVm

<div>
    <div class="messageText">@Model.Result</div>
    <div class="messageText">@Model.Title</div>
    
    <table>
        @foreach (DenominationVm denomination in Model.Denominations) {
        <tr>
            <td>$@denomination.Value</td>
            <td>@denomination.Count</td>
        </tr>
        }
    </table>
</div>

SafeNetATM/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>This demo application was created for SafeNet Consulting, to demonstrate my programming skills</p>

SafeNetATM/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Richard J Werning<br />
    Waukesha, WA 53188<br />
    <abbr title="Phone">P:</abbr>262-719-0627
</address>

<address>
    <strong>Support:</strong> <a href="mailto:rjwerning@gmail.com">rjwerning@gmail.com</a><br />
</address>

SafeNetATM/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>SafeNet ATM</h1>
</div>

<div class="row">
    <div class="col-md-12">
        <h2>Comments on this program</h2>
        <p>
            While the requirements were simple, I chose to over-engineer it for several reasons
        </p>
        <ul>
            <li>Real world applications rarely remain this simple, they always seem to grow over time</li>
            <li>I'm looking for a full-stack position, so it made sense to do both UI and backend</li>
            <li>The purpose of the progam is to demonstrate skills, so I decided to:
                <ul>
                    <li>Use various design patterns (generic, singleton, repository, interface, etc)</li>
                    <li>Use Generics</li>
                    <li>Use Abstract and Concrete classes</li>
                    <li>Add UnitTests</li>
                    <li>Use Ajax</li>
                    <li>Use PartialViews</li>
                </ul>
            </li>
        </ul>
    </div>

    <div>
        @Html.ActionLink("Process ATM Requests", "Index", "ATM")
    </div>
</div>

SafeNetATM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SafeNet ATM", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SafeNet ATM Application, by Rich Werning</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>